name: 'Assign Weekly Reviewer'
description: 'This project is a github action to assign weekly reviewers to a user pull request.'
inputs:
  github-token:
    description: 'secret github token'
    required: true
  reviewers:  # id of input
    description: 'List of reviewers'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'